spring:
  application:
    name: config-server
  profiles:
    active:
    - native, git
  cloud:
    config:
      server:
        git:
         uri: https://github.com/ihuaylupo/config.git
        searchPaths: licensingservice
    
server:
  port: 8071
